### ISSUE TITLE
Cannot read property 'initialized$' of undefined

### ISSUE THREAD

**Issue by gleibfried** [ng2-ui/ng2-map#47] opened 2016-11-30 13:47 UTC
Hello, I want to access my Polygon's properties to make a .getPaths(); on it and did it like this : 

- HTML : 

```
<ng2-map [options]="allOptions" class="horizontal-map">
                        <polygon [editable]="editGeoLocation"
                        [paths]="paths"></polygon></ng2-map>
```

- JavaScript : 

```
     @ViewChild(Polygon) polygon: Polygon
     public polygonObject: google.maps.Polygon
     ngOnInit() {
         this.polygon.initialized$.subscribe(poly => {
             this.polygonObject = poly
             console.log(this.polygonObject)
         })
     }
``` 

But I get a _Cannot read property 'initialized$' of undefined_ error.

To make sure, I also tried doing the example **How to get instance of a map** in the readme file, it says the same but indeed with _mapReady$_.

Has anyone an idea?

**Comment by allenhwkim** [comment] 2016-11-30 16:58
hmm, I don't have idea why this is happening. It works for me, but anyone having the same issue, please report.

**Comment by gleibfried** [comment] 2016-11-30 18:26
Okay, that's strange then, so the Polygon works for you? I'd have liked to try on the project's demo but there's this error in the logs : 
`TypeError: google.maps[this.mapObjectName] is not a constructor`

Okay, so if it works for you it's maybe that it comes from me. I'll keep looking for the problem. And still if anyone has any idea, feel free to tell :)

Thanks!

**Comment by allenhwkim** [comment] 2016-11-30 18:30
My mistake. It was working before, now it does not.
![image](https://cloud.githubusercontent.com/assets/1437734/20765630/210a7fdc-b701-11e6-848b-3bab25c3d8c6.png)

It's a bug status, and I will look into this issue sooner than later.

**Comment by allenhwkim** [comment] 2016-11-30 20:39
It is caused by minification of google maps library done by webpack.

**Comment by allenhwkim** [comment] 2016-11-30 20:41
released with 0.9.1, please verify the changes

**Comment by gleibfried** [comment] 2016-12-02 13:09
Actually that post wasn't about the bug in the example :/ My polygon is still undefined when I enter ngAfterViewInit() :(
I found that we go inside ngAfterViewInit before the polygon is set so the @ViewChild(Polygon) polygon:Polygon variable is still undefined in it, so still this error : 
`Cannot read property 'initialized$' of undefined`

I even tried including it in a setTimeout(() => {...}) with no success.
Otherwise, I just did a button which does a console.log of the polygon and when I click it works.
The thing is that I can't after that make a polygonObject = polygon because then polygonObject, even if it's defined as a google.maps.Polygon, when I try to make a .getPaths() or .getPath() I'm having this error : 
`this.polygonObject.getPaths is not a function`

And also even if the polygon is editable and I've changed some coordinates, the console.log of the polygon isn't updated.

**Comment by allenhwkim** [comment] 2016-12-02 15:03
It works for me,

http://plnkr.co/edit/ohwPfa3CmgZQlGeTCx2h?p=preview

You might have missed to import `Polygon` from `ng2-map`

**Comment by gleibfried** [comment] 2016-12-02 15:05
Yeah I think it's not a problem on the library's side. I think I figured and it seems that there's troubles for the global instanciating when you use custom components inside a component, I put my ng2-map stuff in the above component and here it works now.

Thanks @allenhwkim for the help

**Closed** 2016-12-02 15:06 UTC
Labels: bug
